// <auto-generated />
using HapGp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HapGp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("HapGp.Models.AppConfigModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("AppConfig");
                });

            modelBuilder.Entity("HapGp.Models.BasicApplicationModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("BasicApplication");
                });

            modelBuilder.Entity("HapGp.Models.ProjectModel", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("EndTime");

                    b.Property<string>("ProjectName");

                    b.Property<DateTime?>("StartTime");

                    b.Property<string>("Subtitle");

                    b.Property<int>("TeacherID");

                    b.HasKey("Key");

                    b.ToTable("M_ProjectModels");
                });

            modelBuilder.Entity("HapGp.Models.ProjectSelectModel", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProjectID");

                    b.Property<int>("StudentID");

                    b.HasKey("Key");

                    b.ToTable("M_ProjectSelectModels");
                });

            modelBuilder.Entity("HapGp.Models.StorageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("StorageModel");
                });

            modelBuilder.Entity("HapGp.Models.TestModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("TestModel");
                });

            modelBuilder.Entity("HapGp.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EXT");

                    b.Property<string>("LID")
                        .IsRequired();

                    b.Property<string>("PWD")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HapGp.Models.UserRecordModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<string>("LID")
                        .IsRequired();

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.ToTable("UserRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
